pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'deploy artifacts'

            }
            
        }
            
            
        
    }
}